1080i/Custom_Rss.xml: fix conflicting window ID.
Clashes with 1080i/Custom_Overlay.xml which has window ID 1199 as well, making Kodi print this:

  ERROR: No id specified or id already in use for custom window in Custom_Rss.xml